### ISSUE TITLE
Range for the parameter

### ISSUE THREAD

**Issue by ivanzau** [CDC-DNPAO/CDCAnthro#1]
Is it possible to have values for the "age" parameter that are less than 24?

**Comment by CDC-DNPAO** [comment]
Sorry, but no.  BMI values in the CDC growth charts start at 24 months of age.  At younger ages, the recommendation is to use the WHO growth charts.  You can look at https://github.com/CDC-DNPAO/WHOanthro.  There are also several R programs listed at https://www.cdc.gov/nccdphp/dnpao/growthcharts/resources/r-programs.html
