### ISSUE TITLE
cdcanthro() outputs all NAs

### ISSUE THREAD

**Issue by jaskdb** [CDC-DNPAO/CDCAnthro#2]
Hello! I would like to use this package to get the BMI percentiles for youth in NHANES cycles where the **BMDBMIC** (BMI category) variable did not exist. My example below is for cycle G, which _does_ include **BMDBMIC** because I wanted to be able to verify that the package was producing the expected output.

Presently, the output for the `cdcanthro` function is outputting all NAs. I made sure to exclude any IDs with missing BMI or age information. Do you have an idea about what might be going wrong?

```
#download data from cycle G. if necessary: install.packages("nhanesA")
library(nhanesA) #nhanesA package pulls data straight from web
library(tidyverse)
bmi_g <- nhanes('BMX_G') %>% select(SEQN, BMXBMI, BMDBMIC, BMXHT,BMXWT) # TEST CODE
demo_g <- nhanes('DEMO_G') %>% select(SEQN,RIDEXAGM, DMDHRGND)
test <- merge(bmi_g, demo_g, by= "SEQN")

#clean data according to Github code example
nhanes <- test %>% filter(!is.na(test$BMXBMI) & !is.na(test$RIDEXAGM)) # exclude subjects with missing BMI or age
nhanes$agemos <- nhanes$RIDEXAGM + 0.5 # because agemos is completed number of months

# produces a tibble with all NAs for the derived variables
data <- cdcanthro(nhanes, agemos, BMXWT, BMXHT, BMXBMI, all=TRUE)
```

**Comment by jaskdb** [comment]
Update: after I recoded sex into a factor variable I managed to get the output working. 
`nhanes$sex <- ifelse(nhanes$DMDHRGND == 1, "male", "female")`
`nhanes$sex <- as.factor(nhanes$sex)`

However, I am finding that the BMI percentiles do not match to what I expected when comparing to the **BMDBMIC** variable in NHANES. For example, according to the BMI category variable for underweight (**BMDBMIC** == 1), I would expect to only find that individuals in that category would have **bmip** of less than 5, but I find that it includes some participants with percentiles up to 9.85. Similarly, for the normal weight category, **BMDBMIC** == 2, where I would not expect percentiles above 85, I find that there are participants with percentiles as high as 88. For what it's worth, I find that using the ext_bmiz() from the package `growthcleanr` (which seems to perform the exact same function) results in the same findings. Any ideas?

**Comment by CDC-DNPAO** [comment]
jakkdb - not sure if you saw my comment about growthcleanr, but you're using the wrong variable for sex in NHANES.  Try using 'riagendr' (in caps) rather than DMDHRGND.

Also, a child's sex can now be specified as a variable named 'sex', 'SEX' or 'Sex'
