### ISSUE TITLE
Error in setnames

### ISSUE THREAD

**Issue by ivyyxxx** [CDC-DNPAO/CDCAnthro#5]
I downloaded this package and tried to use in my data. The error always pop up: Error in setnames(cdc_ref, "sex", "sexn") : 
  Items of 'old' not found in column names: [sex]. Consider skip_absent=TRUE. I also tried to run sample code and it showed same error.

Attached is my result when running the example:
## ** Examples

```
data = expand.grid(sex=1:2, agem=120.5, wtk=c(30,60), htc=c(135,144));
data$bmi = data$wtk / (data$htc/100)^2;
data = cdcanthro(data, age=agem, wt=wtk, ht=htc, bmi);
```
```
Error in setnames(cdc_ref, "sex", "sexn"): Items of 'old' not found in column names: [sex]. Consider skip_absent=TRUE.
# OR data = cdcanthro(data, agem, wtk, htc, bmi);
```
`round(data,2)[1:5]`
  sex  agem wtk htc   bmi
1   1 120.5  30 135 16.46
2   2 120.5  30 135 16.46
3   1 120.5  60 135 32.92
4   2 120.5  60 135 32.92
5   1 120.5  30 144 14.47
6   2 120.5  30 144 14.47
7   1 120.5  60 144 28.94
8   2 120.5  60 144 28.94
# setDF(data) to convert to a dataframe

`nhanes   # NHANES data (2015/16 and 2017/18)`
        seqn year strata psu       swt sex agemos    wt    ht  bmi
   1:  83738 2015    120   1  9860.625   2    141  37.2 143.5 18.1
   2:  83739 2015    124   2 46173.307   1     54  16.4 102.1 15.7
   3:  83740 2015    119   1 10963.314   1     14  10.1    NA   NA
   4:  83743 2015    122   2 18249.326   1    217  72.4 166.1 26.2
   5:  83745 2015    126   2 25399.385   2    185  71.7 169.2 25.0
  ---                                                             
7933: 102941 2017    148   1 19672.951   2    180  43.6 147.1 20.1
7934: 102942 2017    147   1 15574.931   2     11   8.9    NA   NA
7935: 102945 2017    146   2 23965.630   1    193  66.5 173.6 22.1
7936: 102951 2017    142   1 35591.310   1     57  23.8 108.9 20.1
7937: 102955 2017    136   1 14871.840   2    175 111.9 156.6 45.6

```
nhanes  = nhanes[!is.na(bmi),] # exclude subjects with missing wt/ht
nhanes$agemos = nhanes$agemos + 0.5   # because agemos is completed number of months
data = cdcanthro(nhanes, age=agemos, wt, ht, bmi, all=TRUE)
```
```
Error in setnames(cdc_ref, "sex", "sexn"): Items of 'old' not found in column names: [sex]. Consider skip_absent=TRUE.
# OR data = cdcanthro(nhanes, agemos, wt, ht, bmi, all=TRUE)
round(data, 2)[1:5]
```
  sex  agem wtk htc   bmi
1   1 120.5  30 135 16.46
2   2 120.5  30 135 16.46
3   1 120.5  60 135 32.92
4   2 120.5  60 135 32.92

**Comment by CDC-DNPAO** [comment]
This is strange.  Do you have an item in your workspace named 'cdc_ref' or
'cdc_ref_data'.  If you do, could you delete them and give it another try -
please let me know if this works.

The function works fine on my Mac until I create a data.frame named
'cdc_ref_data'.

david freedman

**Comment by CDC-DNPAO** [comment]
thanks - I've changed the name of the CDC reference data file to something
I think no one would have in their workspace

david freedman

**Comment by ivyyxxx** [comment]
Thank you!
