### ISSUE TITLE
Error in ':=' seq_, seq_len(.N))

### ISSUE THREAD

**Issue by tormodb** [CDC-DNPAO/CDCAnthro#7]
Hi, thanks for this package! I am having some troubles and get error messages:

`Error in ':=' seq_, seq_len(.N)). :
Check that is.data.table(DT) == TRUE. Otherwise, := and ':='(...) are defined for use in j, once only and in particular ways. See help(":=")`

I have tried to use help, but have not found a workaround. Can you help?

**Comment by CDC-DNPAO** [comment]
This is odd: ':=' is a basic part of data.table and shouldn't cause a problem.  A few things to check: 

(1) Can you run the examples without a problem?
(2) Can you make sure that the data.table package is loaded with a sessionInfo() command?
(3) Make sure that you don't have 'seq_' in your workspace using ls()
(4) Try making your data into a data.table before using the function:  data = as.data.table(data).  I assume that your data is a data frame; is this correct?
(5) Can you run the examples at  ?':='?

If all these things look OK, I'd try to reinstall the package.  If all of this doesn't help, I'd be happy to run a small sample of your data on my computer.  Are you using a Mac, Windows, or Linux?

**Comment by CDC-DNPAO** [comment]
Tormodb - did you ever resolve the problem you were having?  I'm happy to help - just let me know.

**Comment by tormodb** [comment]
Hi, David, I am really sorry but I managed to solve this problem using a different package. I am sure the problem is on my end, we use a manged safe server with no internet connectivity so there is a very high likelihood that something is not set up correctly by our department. Apologies for not getting back to you, and I really appreciate that you followed up on this.

All the best, 
Tormod

**Comment by CDC-DNPAO** [comment]
Tormod - thanks for the information - glad you solved the problem.  We
(CDC) had a (possibly) similar problem with a package - the package worked
on my home PC under windows, ubuntu, and macOS.  But it wouldn't run on a
Windows computer at CDC.

david
