### ISSUE TITLE
Note: possible error in 'setcolorder(dtot, names(dorig), ': unused argument (before = 1)

### ISSUE THREAD

**Issue by zyddmn** [CDC-DNPAO/CDCAnthro#8]
Hi! there's an error message: Note: possible error in 'setcolorder(dtot, names(dorig), ': unused argument (before = 1) during both installing the package and using the function. 

details looks like this: 

`> install.packages( 'https://raw.github.com/CDC-DNPAO/CDCAnthro/master/cdcanthro_0.1.2.tar.gz', type='source', repos=NULL )
trying URL 'https://raw.github.com/CDC-DNPAO/CDCAnthro/master/cdcanthro_0.1.2.tar.gz'
Content type 'application/octet-stream' length 113659 bytes (110 KB)
downloaded 110 KB

* installing *source* package ‘cdcanthro’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
**Note: possible error in 'setcolorder(dtot, names(dorig), ': unused argument (before = 1)** 
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (cdcanthro)`

`> anthdf.cdc <- cdcanthro(anthdf.to.include, age = agem, wt = weight, ht = height, bmi = bmi, all = FALSE)
Error in setcolorder(dtot, names(dorig), before = 1) : 
  unused argument (before = 1)`

**Comment by CDC-DNPAO** [comment]
Thanks for letting me know about this.  I didn't realize that the 'before'
option in 'setcolorder' was a new (Jan 2024) addition.  Can you update your
data.table package and let me know if this solves the problem?  If so, I'll
make notes on github that data.table has to be >= version 1.15.0

thanks, David Freedman

**Comment by CDC-DNPAO** [comment]
oops - I replied too quickly.  I just changed the function so that it would
work with older versions of data.table.  Could you simply try to reinstall
cdcanthro, and let me know if everything's good.

thanks, David

**Comment by zyddmn** [comment]
Thanks! It functioning well now! By the way, can I also ask if there's any R package for age between 0-24 months?

**Comment by CDC-DNPAO** [comment]
glad it's working.  The guidelines from CDC are to use the WHO growth
charts for kids < 2 y.  You can use the whoanthro package at
CDC-DNPAO/WHOanthro (github.com) <https://github.com/CDC-DNPAO/WHOanthro>
for this

The CDC guideline are at
Growth Charts - WHO Child Growth Standards (cdc.gov)
<https://www.cdc.gov/growthcharts/who_charts.htm>

For infants, you can use BMI for age or Weight for length z-scores and
percentiles

david

**Comment by CDC-DNPAO** [comment]
changes setcolorder to NOT use a new option (before=1)
