### ISSUE TITLE
missing .rdb

### ISSUE THREAD

**Issue by eatyourpeas** [CDC-DNPAO/CDCAnthro#9]
Thanks for creating this repo.

Following installation I am getting this message: 
`cannot open file '/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/cdcanthro/R/cdcanthro.rdb': No such file or directory`
The error makes sense because there is no such directory.

Possibly me new to R. Is there an expectation that users download the source data from CDC separately? A more detailed setup guide for noobs like me would be super helpful.

**Comment by CDC-DNPAO** [comment]
Strange.  I just installed it on my wife's M1 MacAir, and it runs fine.  What is the OS version, and what's the R version?
Are you following the installation directions on https://github.com/CDC-DNPAO/CDCAnthro:
install.packages( 'https://raw.github.com/CDC-DNPAO/CDCAnthro/master/cdcanthro_0.1.2.tar.gz', type='source', repos=NULL )

With the above line, cdcanthro.rdb is in the directory that you specified.

Let me know what's up, and I can work on this if you're still having problems.

**Comment by eatyourpeas** [comment]
Amazing thank you! I was not installing from the .tar.gz but directly from the repo. Now working.
Supplementary question if that is allowed... How does CDC like to handle gestational age correction? Do you know?

**Comment by CDC-DNPAO** [comment]
Glad you got it to work.  About gestational age: I'm positive (since I spent 33 years at the CDC) that nothing is done about gestational age.  I should add that the CDC recommendation is to use the WHO growth charts for kids < 24 mos of age.  I've got an R package for this ( https://github.com/CDC-DNPAO/whoAnthro ), or you could use the 'official' WHO package named 'Anthro' on CRAN.

And are you using an M4 iPad? I didn't realize that R could be installed on that.

**Comment by eatyourpeas** [comment]
Not an iPad no - using an M3 macbook and M2 mac studio.

33 years! That is impressive. Thank you that is really helpful.

So for the over 2s there is no gestational age correction, but for the under 2s there is (using the WHO2006 dataset) - is that right? Is that for all babies born under 40 weeks or just those < 37?

I have been working with @statist7 (whom I think you know?) on building UK electronic growth charts and a couple of years back we took the decision to correct for gestational age (if known) across the life course, irrespective of whether term or not. I am putting the CDC/WHO reference in now though and want to make sure that we don't do that for the US. CDCAnthro here super helpful for making sure I use your methodology.

One other related question.. for ages that fall between rows in the reference, do you interpolate and if so which is the preferred way to do this?

**Comment by CDC-DNPAO** [comment]
About interpolation:  WHO gives data (LMS values) for each day of age, so
there's no interpolation. CDC gives data for each month of age, so the
functions I've written use linear interpolation for LMS values between each
month of age to get values for each day of age.  It's actually built into
the cdcanthro, so you don't need to do anything about it.  You can open up
the function and see where I've used 'approx'.

I'm positive that CDC doesn't use a gestational age correction, and I'm
almost positive that WHO also does not.  I think other non-WHO people have
come up with some type of correction.  For example, you can see
https://peditools.org/growthwho/

For more information (than you'd ever want to know) about the WHO charts,
download the PDF at https://www.who.int/publications/i/item/924154693X .
There's no mention of 'gestat' in the document.

**Comment by CDC-DNPAO** [comment]
And please say hi to Tim Cole

**Comment by statist7** [comment]
Hi David,

I'm fairly sure that WHO never talked about gestation correction because all the MGRS neonates were term by definition. So they had no data to do the correction.

**Comment by eatyourpeas** [comment]
Thank you both. This is great context.

**Comment by CDC-DNPAO** [comment]
thanks.  I'm forgetting more and more each day in retirement.

Not sure if you use data.table in R, but there's now a Mac binary that
allows for multiple threads.  So no need to use Homebrew to download clang
and llvm, and a makeover file is no longer needed.
